version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo "Region: $AWS_REGION"
      - echo "Repo: $REPOSITORY_URI"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export IMAGE_TAG="$CODEBUILD_BUILD_NUMBER"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t coworking-app:$IMAGE_TAG .
      - docker tag coworking-app:$IMAGE_TAG $REPOSITORY_URI:coworking-app-$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:coworking-app-$IMAGE_TAG
