version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    REPOSITORY_URI: 205144097027.dkr.ecr.us-east-1.amazonaws.com/coworking-app-repo

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export IMAGE_TAG="$CODEBUILD_BUILD_NUMBER"

  build:
    commands:
      - docker build -t coworking-app:$IMAGE_TAG .
      - docker tag coworking-app:$IMAGE_TAG $REPOSITORY_URI:coworking-app-$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:coworking-app-$IMAGE_TAG
